version: '3.7'
services:
  server:
    build:
      context: ./estadao-news-api
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3001:3001'
    volumes:
      - ./estadao-news-api:/app
      - /app/node_modules
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: estadao
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - backend
    depends_on:
      - mysql

  mysql:
    container_name: database
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estadao
      MYSQL_USER: api
      MYSQL_PASSWORD: 1020304050
    networks:
      - backend

  frontend:
    build:
      context: ./estadao-news-app
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '80:80'
    environment:
      REACT_APP_URL_BASE: http://server:3001
    depends_on:
      - server
    networks:
      - backend

networks:
  backend:
    driver: bridge
