version: '3.7'
services:
  mysql:
    container_name: database_teste
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estadaodb
      MYSQL_USER: estadao
      MYSQL_PASSWORD: estadao
    networks:
      - backend

networks:
  backend:
    driver: bridge
