version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: news_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newsdb
      MYSQL_USER: news
      MYSQL_PASSWORD: news
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - news_network

  server:
    build:
      context: ./news-api
      dockerfile: Dockerfile
    container_name: news_api_server
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_TYPE: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: newsdb
    depends_on:
      - mysql
    networks:
      - news_network

  frontend:
    build:
      context: ./news-app
      dockerfile: Dockerfile
    container_name: news_frontend
    ports:
      - "80:80"
    environment:
      REACT_APP_URL_BASE: http://server:3001
    depends_on:
      - server
    networks:
      - news_network

networks:
  news_network:
    driver: bridge

volumes:
  mysql-data:
